primary_account:
  email: drlucyatuomation@api-for-warp-drive.iam.gserviceaccount.com
  roles:
    - aiplatform.admin
    - aiplatform.colabServiceAgent
    - aiplatform.customCodeServiceAgent
    - apigateway.admin
    - apigateway.serviceAgent
    - cloudbuild.builds.builder
    - compute.networkUser
    - container.admin
    - firebase.managementServiceAgent
    - iam.oauthClientAdmin
    - logging.admin
    - owner
    - secretmanager.admin
    - source.admin
    - storage.admin

endpoints:
  - name: Dr-Lucy-01
    id: 6296186210691842048
  - name: Dr-Lucy-02
    id: 6301815710226055168
  - name: Dr-Lucy-03
    id: 3426267348149993472