launch_sequence:
  service_account: drlucyatuomation@api-for-warp-drive.iam.gserviceaccount.com

  agents:
    dr_lucy:
      - name: Dr-Lucy-01
        id: "6296186210691842048"
        region: us-west1
        memory: "96Gi"
      - name: Dr-Lucy-02
        id: "6301815710226055168"
        region: us-west1
        memory: "96Gi"
      - name: Dr-Lucy-03
        id: "3426267348149993472"
        region: us-west1
        memory: "96Gi"

    super_claude:
      name: Super-Claude-1
      id: "4313929473532624896"
      region: us-west4
      model: knowledge-base-model

  network:
    load_balancer: "34.8.193.106:443"
    ssl_cert: "sc2100cool"
    tier: "PREMIUM"