apiVersion: networking.gke.io/v1
kind: LoadBalancer
metadata:
  name: anthology-url-map
spec:
  frontend:
    protocol: HTTPS
    port: 443
    ip: 34.8.193.106
    ssl:
      certificateName: sc2100cool
    networkTier: PREMIUM
  
  backend:
    name: lb-ip-2100-cool-backend
    timeoutSeconds: 60
    healthCheck:
      name: tcp-443-health-check
      type: TCP
      port: 443
  
  dns:
    domain: .2100.cool
    ttl: 3600  # 1 hour

  routing:
    defaultService: lb-ip-2100-cool-backend